sudo: false
language: python
python:
  - "2.7"
  - "3.4"
install: pip install -r requirements.txt
before_script:
  # manually make our own virtualenv, so we don't need to worry about python version paths
  - deactivate
  - virtualenv .
  - source bin/activate
  - pip install pep8
  - pip install coverage
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
  - python manage.py migrate
  - coverage run --source=stormcell/ --omit=stormcell/migrations/* manage.py test stormcell
script:
  - pep8 stormcell/ --exclude=migrations
